### ISSUE TITLE
cPanel on docker persistent volumes

### ISSUE THREAD

**Issue by IlyasDeckers** [mirhosting/cPanel-docker#4]
Hey,

I've been struggling for days now with cPanel on docker. How do you guys handle persistent data with cPanel on docker? For normal webservers/apps this is quite straightforward, but when it comes to whole operating systems I get lost somehow.

Can you give some pointers on how to handle persistent data with cPanel in case of node failure?

Thanks in advance!!

**Comment by mirhosting** [comment]
Sorry for delay, we were not subscribed to updates here
You definitely don't have to have persistence for whole system, its abusing the whole idea.
In this case having cPanel in dockers actually also abusing idea of microservices :)

Why actually you want to have persistent data? In case of MIRhosting Cloud data will kept even in you shutdown the container. In case of other solutions it might be different, then it should be adjusted.

**Comment by IlyasDeckers** [comment]
I am looking to run (or at least try) to run cPanel on a docker swarm cluster as a service, in terms of high availability and scale ability this would be awesome. 
At the moment I have a ceph backend that holds all the data for my docker containers in the swarm. In case of rescheduling, scaling or node failure a container can pop up on any node in the cluster, this is were the fun begins, docker volumes are bound to the host and almost all available volume plugins do not work with a single volume for multiple contaners (+ multiple hosts) 
This is why I mostly work with CephFS mounted on the docker swarm hosts and the bind the data to the container.
``` 
docker service create \
    --name some_service
    --mount type=bind,source=/var/lib/data/some_app,target=/var/www/html
    --replicas 1
nginx
``` 
I am writing a blog post about this. Large docker swarm clusters and persistent data, with services that scale horizontally don't play nice togheter. I'll post it here if you are intrested.

**Comment by mirhosting** [comment]
You basically have 2 ways to accomplish it
1. Exactly how our Cloud Platform is working:
- Storage is distributed across multiple storage nodes (yes, like ceph but production-ready and faster)
- High Availability - if Compute node fail, orchestrator start it in next available node, in most cases even restart is not needed

So, here all redundant and orchestration part is done on infrastructure level

2. Trying to accomplish same story on Docker swarm level. Honestly, I am sure its possible to do as a prove, but not really for production. Simply, because cPanel is not a application, its full-stack hosting software and you will get a lot of issues running such setup. However, I am up to help and support you as much as possible.

If you like, we can provide you with free dev usage on MIRhosting Cloud Platform. After we will upgrade our Cloud Platform to version 5.0.6, we will regain support of native docker swarm. Upgrade will be finalized by end of May.
https://github.com/jelastic-jps/docker-native/tree/master/docker-swarm
Send a ping to marketing@mirhosting.com
